{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy-xml",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "groovydocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "groovydoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.6-groovydoc.jar",
          "url": "groovy-xml-4.0.6-groovydoc.jar",
          "size": 259589,
          "sha512": "0554d59fca47c98910a28f698bfc2973d12ad0c6a4828061a62f004eedbaffd8de7cb3784f5fe3e7fa05bd07d7e00c5a96ddcb2688721f4ae3982a6887fd53c5",
          "sha256": "0d4b7fa3e58bb89fa7a487628f49c831642bdfae4668c2984d35eaf172556c6d",
          "sha1": "61bd5c750f3634dd00a7460c53732fa79465a89b",
          "md5": "8609cc1d3b35c0c0c2421049bad3f66c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.6-javadoc.jar",
          "url": "groovy-xml-4.0.6-javadoc.jar",
          "size": 319946,
          "sha512": "42c5e9792ffd11fc7ca4f072e4bb14a0928bc39209ad3990fa980aa0d265e5a64db7d2d4710c5f81678ce6f8ecbbb64ce3c2854b7b35da0a9292f9fd401a2484",
          "sha256": "d786c38a6c0611775d21113d4ba734bd3d6ee4f4571afe9040ecf6fb40a3677c",
          "sha1": "8ee21d90da35d7f34ccddffbc3d1175d8226a336",
          "md5": "3e96c22d7c29e3dc57df1118fc5ce0fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-xml-4.0.6-sources.jar",
          "url": "groovy-xml-4.0.6-sources.jar",
          "size": 98897,
          "sha512": "7711edcb68ce57181738794e38cce51a3cd6fde1a273f62c079f3cbff080ad6a13cf2ae59f1ead0923f5a4995266a4a49bc7b7f7412c198b610d9621576c9681",
          "sha256": "209e7db238d35e721cb07a780badd36a660e622a2f3f7c99328689c0860c4763",
          "sha1": "d7f742c97164a3aace85ef3cc42eab8c5c99d044",
          "md5": "3be580d416e85baa1da0cf16e508e80c"
        }
      ]
    },
    {
      "name": "groovyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-xml-4.0.6.jar",
          "url": "groovy-xml-4.0.6.jar",
          "size": 230236,
          "sha512": "cda106683c6e80bd99debf4c52eb2ad47443e862a2b4dd3150b0335b47f5e7d04d427ebf03718f5d27d10d7908e228e1f3b7931780d99849e190fcd5d4049a28",
          "sha256": "22f37a69dad193ff71618dc5f3870d334e70271abbe077b26265113b4e2c46e7",
          "sha1": "0a05e4f0e902b43764ff1161797f5079d3608143",
          "md5": "a4a93d392353b9af97008a6234616be5"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-xml",
          "version": "4.0.6"
        },
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-xml",
          "version": "4.0.6"
        }
      ]
    },
    {
      "name": "groovyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.6"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-xml-4.0.6.jar",
          "url": "groovy-xml-4.0.6.jar",
          "size": 230236,
          "sha512": "cda106683c6e80bd99debf4c52eb2ad47443e862a2b4dd3150b0335b47f5e7d04d427ebf03718f5d27d10d7908e228e1f3b7931780d99849e190fcd5d4049a28",
          "sha256": "22f37a69dad193ff71618dc5f3870d334e70271abbe077b26265113b4e2c46e7",
          "sha1": "0a05e4f0e902b43764ff1161797f5079d3608143",
          "md5": "a4a93d392353b9af97008a6234616be5"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-xml",
          "version": "4.0.6"
        },
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-xml",
          "version": "4.0.6"
        }
      ]
    }
  ]
}
